export type SelectOption = {
  label: string;
  value: string;
};

export type StudentDirectoryRow = {
  id: string;
  photoUrl: string | null;
  studentCode: string;
  fullName: string;
  agentCode?: string;
  agentName?: string;
  instituteCode: string;
  instituteName: string;
  tradeName: string;
  unitNumber: string;
  session: string;
  yearLabel: string;
  mobile: string;
  status: string;
  lifecycleStage?: string;
  documentsStatus: string;
  eligibilityStatus: string;
  dueAmount: string;
};

export type StudentProfileData = {
  id: string;
  studentCode: string;
  admissionNumber: string | null;
  enrollmentNumber: string | null;
  photoUrl: string | null;
  fullName: string;
  instituteName: string;
  instituteCode: string;
  tradeName: string;
  session: string;
  yearLabel: string;
  unitNumber: string | null;
  status: string;
  admissionStatusLabel: string | null;
  admissionDate: string | null;
  admissionType: string | null;
  seatType: string | null;
  rollNumber: string | null;
  batchLabel: string | null;
  shiftLabel: string | null;
  mobile: string;
  alternateMobile: string | null;
  email: string | null;
  dateOfBirth: string | null;
  gender: string | null;
  category: string | null;
  caste: string | null;
  religion: string | null;
  incomeDetails: string | null;
  domicileDetails: string | null;
  minorityStatus: boolean;
  disabilityStatus: boolean;
  maritalStatus: string | null;
  signatureUrl: string | null;
  address: string | null;
  fatherName: string | null;
  motherName: string | null;
  aadhaarMasked: string | null;
  paymentMode: string | null;
  parent: {
    relation: string;
    name: string;
    mobile: string | null;
    aadhaarMasked: string | null;
  } | null;
  education: {
    boardUniversity: string | null;
    schoolName: string | null;
    certificateNumber: string | null;
    rollNumber: string | null;
    passingYear: number | null;
    percentage: string | null;
    isPassed: boolean;
    verificationStatus: string;
  } | null;
  fees: {
    collectionMode: string;
    instituteDecidedFee: string | null;
    feesIfScholarship: string | null;
    feesIfNoScholarship: string | null;
    agentCommittedFee: string | null;
    scholarshipApplied: boolean;
    convertedFromAgent: boolean;
    conversionDate: string | null;
    conversionReason: string | null;
    reminderCount: number;
    lastReminderDate: string | null;
    finalFees: string;
    paidAmount: string;
    dueAmount: string;
    paymentStatus: string;
    practicalExamEligible: boolean;
    adminOverride: boolean;
    finalStatus: string | null;
    transactions: Array<{
      id: string;
      receiptNo: string;
      transactionDate: string;
      amountPaid: string;
      paymentMode: string;
      referenceNo: string | null;
      remark: string | null;
    }>;
  } | null;
  scholarship: {
    status: string;
    scholarshipId: string | null;
    incomeCertificateNumber: string | null;
    queryText: string | null;
    approvedDate: string | null;
    creditedAmount: string | null;
    creditDate: string | null;
    incomeCertificateOk: boolean;
    bankVerified: boolean;
    aadhaarVerified: boolean;
    casteCertificateOk: boolean;
  } | null;
  prnScvt: {
    entRollNumber: string | null;
    admissionStatus: string | null;
    prnNumber: string | null;
    scvtRegistrationNumber: string | null;
    verificationStatus: string;
    uploadDate: string | null;
    remark: string | null;
  } | null;
  examStatus: {
    examFeePaid: boolean;
    hallTicketIssuedOn: string | null;
    tradePracticalResult: string;
    onlineTheoryResult: string;
    practicalExamAppearance: string;
    practicalAttemptCount: number;
    theoryAttemptCount: number;
    nextPracticalAttemptDate: string | null;
    nextTheoryAttemptDate: string | null;
    practicalReappearStatus: string;
    theoryReappearStatus: string;
    practicalEligibleReappear: boolean;
    theoryEligibleReappear: boolean;
    adminOverrideReason: string | null;
    resultPublished: boolean;
    resultDeclaredOn: string | null;
    remark: string | null;
  } | null;
  undertaking: {
    verificationCode: string | null;
    generatedUrl: string | null;
    generationStatus: string;
    generatedOn: string | null;
    printCount: number;
    signedDocumentUrl: string | null;
    signedStatus: string;
  } | null;
  documents: Array<{
    id: string;
    documentType: string;
    ownerType: string;
    originalName: string;
    fileUrl: string;
    verificationStatus: string;
    remarks: string | null;
    createdAt: string;
  }>;
  attendance: {
    totalMarkedDays: number;
    attendedDays: number;
    absentDays: number;
    attendancePercentage: string;
    monthlySummary: Array<{
      monthLabel: string;
      totalMarkedDays: number;
      attendedDays: number;
      absentDays: number;
      attendancePercentage: string;
    }>;
    recentRecords: Array<{
      id: string;
      recordDate: string;
      status: string;
      checkInAt: string | null;
      checkOutAt: string | null;
      note: string | null;
    }>;
  };
  certificates: Array<{
    id: string;
    certificateType: string;
    certificateNumber: string;
    verificationCode: string;
    issueDate: string;
    printCount: number;
    lastPrintedAt: string | null;
    note: string | null;
  }>;
  noDues: {
    totalDepartments: number;
    clearedDepartments: number;
    pendingDepartments: number;
    isReady: boolean;
  };
  supportCases: Array<{
    id: string;
    grievanceNo: string;
    category: string;
    title: string;
    priority: string;
    status: string;
    createdAt: string;
    resolutionNote: string | null;
  }>;
  workflow: {
    documentsStatus: string;
    nextStudentStatus: string;
    blockers: string[];
    rules: Array<{
      code: string;
      label: string;
      required: boolean;
      uploaded: boolean;
      verificationStatus: string;
    }>;
  };
};

export type DashboardMetric = {
  label: string;
  value: string;
  helper?: string;
};

export type AdmissionFormDefaults = {
  sourceEnquiryId: string;
  instituteId: string;
  tradeId: string;
  enrollmentNumber: string;
  unitNumber: string;
  session: string;
  yearLabel: string;
  admissionDate: string;
  admissionType: string;
  admissionStatusLabel: string;
  seatType: string;
  rollNumber: string;
  batchLabel: string;
  shiftLabel: string;
  fullName: string;
  dateOfBirth: string;
  mobile: string;
  alternateMobile: string;
  email: string;
  gender: string;
  category: string;
  caste: string;
  religion: string;
  incomeDetails: string;
  domicileDetails: string;
  minorityStatus: boolean;
  disabilityStatus: boolean;
  maritalStatus: string;
  country: string;
  stateName: string;
  district: string;
  tehsil: string;
  block: string;
  ward: string;
  areaVillage: string;
  address: string;
  fatherName: string;
  motherName: string;
  studentAadhaar: string;
  parentRelation: string;
  parentName: string;
  parentMobile: string;
  parentAadhaar: string;
  qualifications: Array<{
    qualificationLevel: string;
    schoolName: string;
    boardUniversity: string;
    certificateNumber: string;
    passingYear: string;
    percentage: string;
    rollNumber: string;
  }>;
  isPassed: boolean;
  scholarshipApplied: boolean;
  incomeCertificateNumber: string;
  admissionMode: string;
  agentId: string;
  notes: string;
};
